[workspace]
resolver = "2"
members = [
  "crates/envoy-files-core",
  "crates/envoy-files-filter",
  "crates/envoy-files-io",
  "crates/envoy-files-itest",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
repository = "https://github.com/curioswitch/envoy-files"
license = "Apache-2.0"

[workspace.dependencies]
crossbeam-channel = "0.5.15"
envoy-files-core = { path = "crates/envoy-files-core" }
envoy-files-io = { path = "crates/envoy-files-io" }
envoy-proxy-dynamic-modules-rust-sdk = {
  git = "https://github.com/anuraaga/envoy",
  rev = "245289bc0d9664a885c71a23df1deccb0511fb44"
}
yaml-rust2 = "0.11.0"

[profile.release]
lto = "thin"
